baseurl      = "https://leandrofabianjr.github.io/"
title        = "Leandro Fabian Jr."
languageCode = "br"
defaultContentLanguage = "br"

[menu]
  [[menu.main]]
      identifier = "projetos"
      name       = "Projetos"
      title = "Meus projetos"
      url        = "/projects"
  [[menu.main]]
      identifier = "about"
      name = "Sobre"
      title = "Sobre mim"
        url = "/about"